<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Esquema Fatorial (3 Fatores) | Aplicações práticas do software R para Agronomia</title>
  <meta name="description" content="Este é um …" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Esquema Fatorial (3 Fatores) | Aplicações práticas do software R para Agronomia" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este é um …" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Esquema Fatorial (3 Fatores) | Aplicações práticas do software R para Agronomia" />
  
  <meta name="twitter:description" content="Este é um …" />
  

<meta name="author" content="Gabriel Danilo Shimizu" />


<meta name="date" content="2020-03-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="delineamento-inteiramente-casualizado.html"/>
<link rel="next" href="esquema-de-parcelas-subdivididas.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Aplicações práticas do software R para Agronomia</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Apresentação</a></li>
<li class="chapter" data-level="2" data-path="estatística-experimental.html"><a href="estatística-experimental.html"><i class="fa fa-check"></i><b>2</b> Estatística Experimental</a></li>
<li class="chapter" data-level="3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html"><i class="fa fa-check"></i><b>3</b> Delineamento Inteiramente Casualizado</a><ul>
<li class="chapter" data-level="3.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#vantagens"><i class="fa fa-check"></i><b>3.1</b> Vantagens</a></li>
<li class="chapter" data-level="3.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#desvantagens"><i class="fa fa-check"></i><b>3.2</b> Desvantagens</a></li>
<li class="chapter" data-level="3.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático-para-dic"><i class="fa fa-check"></i><b>3.3</b> Modelo matemático para DIC</a></li>
<li class="chapter" data-level="3.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#hipóteses-e-modelo"><i class="fa fa-check"></i><b>3.4</b> Hipóteses e Modelo</a></li>
<li class="chapter" data-level="3.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#croqui-para-dic"><i class="fa fa-check"></i><b>3.5</b> Croqui para DIC</a></li>
<li class="chapter" data-level="3.6" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-1-4"><i class="fa fa-check"></i><b>3.6</b> Exemplo 1</a></li>
<li class="chapter" data-level="3.7" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#estatística-descritiva-2"><i class="fa fa-check"></i><b>3.7</b> Estatística descritiva</a><ul>
<li class="chapter" data-level="3.7.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#por-inoculação"><i class="fa fa-check"></i><b>3.7.1</b> Por Inoculação</a></li>
<li class="chapter" data-level="3.7.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#por-época-de-aplicação"><i class="fa fa-check"></i><b>3.7.2</b> Por época de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#gráficos-exploratórios-3"><i class="fa fa-check"></i><b>3.8</b> Gráficos exploratórios</a><ul>
<li class="chapter" data-level="3.8.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#gráfico-de-caixas-5"><i class="fa fa-check"></i><b>3.8.1</b> Gráfico de Caixas</a></li>
<li class="chapter" data-level="3.8.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#gráfico-de-interação"><i class="fa fa-check"></i><b>3.8.2</b> Gráfico de interação</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#análise-de-variância-7"><i class="fa fa-check"></i><b>3.9</b> Análise de Variância</a></li>
<li class="chapter" data-level="3.10" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#pressuposições-6"><i class="fa fa-check"></i><b>3.10</b> Pressuposições</a><ul>
<li class="chapter" data-level="3.10.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#normalidade-dos-erros-9"><i class="fa fa-check"></i><b>3.10.1</b> Normalidade dos erros</a></li>
<li class="chapter" data-level="3.10.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#homogeneidade-de-variâncias-4"><i class="fa fa-check"></i><b>3.10.2</b> Homogeneidade de variâncias</a></li>
<li class="chapter" data-level="3.10.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#independência-dos-erros-6"><i class="fa fa-check"></i><b>3.10.3</b> Independência dos erros</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#teste-de-comparações-2"><i class="fa fa-check"></i><b>3.11</b> Teste de comparações</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html"><i class="fa fa-check"></i><b>4</b> Esquema Fatorial (3 Fatores)</a><ul>
<li class="chapter" data-level="4.1" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#tipos-de-efeitos-avaliados-1"><i class="fa fa-check"></i><b>4.1</b> Tipos de efeitos avaliados</a></li>
<li class="chapter" data-level="4.2" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#vantagens-3"><i class="fa fa-check"></i><b>4.2</b> Vantagens</a></li>
<li class="chapter" data-level="4.3" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#desvantagens-3"><i class="fa fa-check"></i><b>4.3</b> Desvantagens</a></li>
<li class="chapter" data-level="4.4" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#modelo-estatístico-1"><i class="fa fa-check"></i><b>4.4</b> Modelo estatístico</a></li>
<li class="chapter" data-level="4.5" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#hipóteses-e-modelo-3"><i class="fa fa-check"></i><b>4.5</b> Hipóteses e modelo</a></li>
<li class="chapter" data-level="4.6" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#exemplo-1-5"><i class="fa fa-check"></i><b>4.6</b> Exemplo 1</a></li>
<li class="chapter" data-level="4.7" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#conjunto-de-dados-6"><i class="fa fa-check"></i><b>4.7</b> Conjunto de dados</a></li>
<li class="chapter" data-level="4.8" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#análise-exploratória-dos-dados"><i class="fa fa-check"></i><b>4.8</b> Análise Exploratória dos dados</a><ul>
<li class="chapter" data-level="4.8.1" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#análise-exploratória-dos-dados-geral"><i class="fa fa-check"></i><b>4.8.1</b> Análise Exploratória dos dados (Geral)</a></li>
<li class="chapter" data-level="4.8.2" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#análise-exploratória-dos-dados-fator-1"><i class="fa fa-check"></i><b>4.8.2</b> Análise Exploratória dos dados (Fator 1)</a></li>
<li class="chapter" data-level="4.8.3" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#análise-exploratória-dos-dados-fator-3"><i class="fa fa-check"></i><b>4.8.3</b> Análise Exploratória dos dados (Fator 3)</a></li>
<li class="chapter" data-level="4.8.4" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#análise-exploratória-dos-dados-juntando-tratamentos"><i class="fa fa-check"></i><b>4.8.4</b> Análise Exploratória dos dados (Juntando tratamentos)</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#gráfico-exploratório"><i class="fa fa-check"></i><b>4.9</b> Gráfico exploratório</a><ul>
<li class="chapter" data-level="4.9.1" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#gráfico-de-caixas-6"><i class="fa fa-check"></i><b>4.9.1</b> Gráfico de caixas</a></li>
<li class="chapter" data-level="4.9.2" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#gráfico-de-interação-1"><i class="fa fa-check"></i><b>4.9.2</b> Gráfico de interação</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#análise-de-variância-8"><i class="fa fa-check"></i><b>4.10</b> Análise de variância</a></li>
<li class="chapter" data-level="4.11" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#pressuposições-7"><i class="fa fa-check"></i><b>4.11</b> Pressuposições</a><ul>
<li class="chapter" data-level="4.11.1" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#normalidade-dos-erros-10"><i class="fa fa-check"></i><b>4.11.1</b> Normalidade dos erros</a></li>
<li class="chapter" data-level="4.11.2" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#homogeneidade-das-variâncias-5"><i class="fa fa-check"></i><b>4.11.2</b> Homogeneidade das variâncias</a></li>
<li class="chapter" data-level="4.11.3" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#independência-dos-erros-7"><i class="fa fa-check"></i><b>4.11.3</b> Independência dos erros</a></li>
<li class="chapter" data-level="4.11.4" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#gráfico-de-residuos-padronizados"><i class="fa fa-check"></i><b>4.11.4</b> Gráfico de residuos padronizados</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#teste-de-comparação"><i class="fa fa-check"></i><b>4.12</b> Teste de comparação</a><ul>
<li class="chapter" data-level="4.12.1" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#pacote-expdes.pt"><i class="fa fa-check"></i><b>4.12.1</b> Pacote ExpDes.pt</a></li>
<li class="chapter" data-level="4.12.2" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#pacote-easyanova"><i class="fa fa-check"></i><b>4.12.2</b> Pacote easyanova</a></li>
</ul></li>
<li class="chapter" data-level="4.13" data-path="esquema-fatorial-3-fatores.html"><a href="esquema-fatorial-3-fatores.html#tabela-final"><i class="fa fa-check"></i><b>4.13</b> Tabela Final</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html"><i class="fa fa-check"></i><b>5</b> Esquema de Parcelas Subdivididas</a><ul>
<li class="chapter" data-level="5.1" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#vantagens-4"><i class="fa fa-check"></i><b>5.1</b> Vantagens</a></li>
<li class="chapter" data-level="5.2" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#desvantagens-4"><i class="fa fa-check"></i><b>5.2</b> Desvantagens</a></li>
<li class="chapter" data-level="5.3" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#modelo-estatístico-2"><i class="fa fa-check"></i><b>5.3</b> Modelo estatístico</a></li>
<li class="chapter" data-level="5.4" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#hipóteses-e-modelo-4"><i class="fa fa-check"></i><b>5.4</b> Hipóteses e modelo</a></li>
<li class="chapter" data-level="5.5" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#croqui-em-dic-1"><i class="fa fa-check"></i><b>5.5</b> Croqui em DIC</a></li>
<li class="chapter" data-level="5.6" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#croqui-em-dbc-1"><i class="fa fa-check"></i><b>5.6</b> Croqui em DBC</a></li>
<li class="chapter" data-level="5.7" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#exemplo-1-6"><i class="fa fa-check"></i><b>5.7</b> Exemplo 1</a></li>
<li class="chapter" data-level="5.8" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#estatística-descritiva-3"><i class="fa fa-check"></i><b>5.8</b> Estatística descritiva</a><ul>
<li class="chapter" data-level="5.8.1" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#fator-1-linha-e-entrelinha"><i class="fa fa-check"></i><b>5.8.1</b> Fator 1 (Linha e Entrelinha)</a></li>
<li class="chapter" data-level="5.8.2" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#fator-2-manejo"><i class="fa fa-check"></i><b>5.8.2</b> Fator 2 (Manejo)</a></li>
<li class="chapter" data-level="5.8.3" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#repetição"><i class="fa fa-check"></i><b>5.8.3</b> Repetição</a></li>
<li class="chapter" data-level="5.8.4" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#juntando-os-fatores"><i class="fa fa-check"></i><b>5.8.4</b> Juntando os fatores</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#gráficos-exploratórios-4"><i class="fa fa-check"></i><b>5.9</b> Gráficos exploratórios</a><ul>
<li class="chapter" data-level="5.9.1" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#gráfico-de-caixas-boxplot-2"><i class="fa fa-check"></i><b>5.9.1</b> Gráfico de caixas (<em>Boxplot</em>)</a></li>
<li class="chapter" data-level="5.9.2" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#interação"><i class="fa fa-check"></i><b>5.9.2</b> Interação</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#análise-de-variância-9"><i class="fa fa-check"></i><b>5.10</b> Análise de Variância</a><ul>
<li class="chapter" data-level="5.10.1" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#usando-o-pacote-agricolae-1"><i class="fa fa-check"></i><b>5.10.1</b> Usando o pacote agricolae</a></li>
<li class="chapter" data-level="5.10.2" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#usando-o-pacote-easyanova-1"><i class="fa fa-check"></i><b>5.10.2</b> Usando o pacote easyanova</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#pressupostos"><i class="fa fa-check"></i><b>5.11</b> Pressupostos</a><ul>
<li class="chapter" data-level="5.11.1" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#normalidade-dos-erros-11"><i class="fa fa-check"></i><b>5.11.1</b> Normalidade dos erros</a></li>
<li class="chapter" data-level="5.11.2" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#homogeneidade-de-variâncias-5"><i class="fa fa-check"></i><b>5.11.2</b> Homogeneidade de variâncias</a></li>
<li class="chapter" data-level="5.11.3" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#independência-dos-erros-8"><i class="fa fa-check"></i><b>5.11.3</b> Independência dos erros</a></li>
<li class="chapter" data-level="5.11.4" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#análise-gráfica"><i class="fa fa-check"></i><b>5.11.4</b> Análise Gráfica</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#teste-de-comparações-múltiplas"><i class="fa fa-check"></i><b>5.12</b> Teste de comparações múltiplas</a><ul>
<li class="chapter" data-level="5.12.1" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#pelo-pacote-easyanova"><i class="fa fa-check"></i><b>5.12.1</b> Pelo pacote easyanova</a></li>
<li class="chapter" data-level="5.12.2" data-path="esquema-de-parcelas-subdivididas.html"><a href="esquema-de-parcelas-subdivididas.html#pelo-pacote-expdes.pt"><i class="fa fa-check"></i><b>5.12.2</b> Pelo pacote ExpDes.pt</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html"><i class="fa fa-check"></i><b>6</b> Polinômios Ortogonais</a><ul>
<li class="chapter" data-level="6.1" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#teste-f"><i class="fa fa-check"></i><b>6.1</b> Teste F</a></li>
<li class="chapter" data-level="6.2" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#quadro-da-análise-de-variância"><i class="fa fa-check"></i><b>6.2</b> Quadro da Análise de variância</a></li>
<li class="chapter" data-level="6.3" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#exemplo-1-7"><i class="fa fa-check"></i><b>6.3</b> Exemplo 1</a><ul>
<li class="chapter" data-level="6.3.1" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#conjunto-de-dados-7"><i class="fa fa-check"></i><b>6.3.1</b> Conjunto de dados</a></li>
<li class="chapter" data-level="6.3.2" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#média-e-variância"><i class="fa fa-check"></i><b>6.3.2</b> Média e Variância</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#análise-de-variância-10"><i class="fa fa-check"></i><b>6.4</b> Análise de Variância</a></li>
<li class="chapter" data-level="6.5" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#análise-de-variância-para-matéria-seca"><i class="fa fa-check"></i><b>6.5</b> Análise de Variância para Matéria Seca</a></li>
<li class="chapter" data-level="6.6" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#polinômio-até-4-grau"><i class="fa fa-check"></i><b>6.6</b> Polinômio até 4 grau</a></li>
<li class="chapter" data-level="6.7" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#polinômio-de-3-grau"><i class="fa fa-check"></i><b>6.7</b> Polinômio de 3 grau</a></li>
<li class="chapter" data-level="6.8" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#polinômio-de-2-grau"><i class="fa fa-check"></i><b>6.8</b> Polinômio de 2 grau</a></li>
<li class="chapter" data-level="6.9" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#polinômio-de-1-grau"><i class="fa fa-check"></i><b>6.9</b> Polinômio de 1 grau</a></li>
<li class="chapter" data-level="6.10" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#coeficientes-do-modelo"><i class="fa fa-check"></i><b>6.10</b> Coeficientes do modelo</a></li>
<li class="chapter" data-level="6.11" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#curva-estimada"><i class="fa fa-check"></i><b>6.11</b> Curva Estimada</a></li>
<li class="chapter" data-level="6.12" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#usando-o-expdes.pt-1"><i class="fa fa-check"></i><b>6.12</b> Usando o ExpDes.pt</a></li>
<li class="chapter" data-level="6.13" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#gráfico"><i class="fa fa-check"></i><b>6.13</b> Gráfico</a></li>
<li class="chapter" data-level="6.14" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#gráfico-somente-com-a-média"><i class="fa fa-check"></i><b>6.14</b> Gráfico somente com a média</a></li>
<li class="chapter" data-level="6.15" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#exemplo-2-3"><i class="fa fa-check"></i><b>6.15</b> Exemplo 2</a></li>
<li class="chapter" data-level="6.16" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#análise-de-variância-11"><i class="fa fa-check"></i><b>6.16</b> Análise de Variância</a></li>
<li class="chapter" data-level="6.17" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#pressuposições-8"><i class="fa fa-check"></i><b>6.17</b> Pressuposições</a><ul>
<li class="chapter" data-level="6.17.1" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#normalidade-dos-erros-12"><i class="fa fa-check"></i><b>6.17.1</b> Normalidade dos erros</a></li>
<li class="chapter" data-level="6.17.2" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#homogeneidade-das-variâncias-6"><i class="fa fa-check"></i><b>6.17.2</b> Homogeneidade das Variâncias</a></li>
<li class="chapter" data-level="6.17.3" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#independência-dos-erros-9"><i class="fa fa-check"></i><b>6.17.3</b> Independência dos erros</a></li>
</ul></li>
<li class="chapter" data-level="6.18" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#coeficientes-do-modelo-1"><i class="fa fa-check"></i><b>6.18</b> Coeficientes do modelo</a></li>
<li class="chapter" data-level="6.19" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#usando-o-expdes.pt-2"><i class="fa fa-check"></i><b>6.19</b> Usando o ExpDes.pt</a></li>
<li class="chapter" data-level="6.20" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#curva-estimada-1"><i class="fa fa-check"></i><b>6.20</b> Curva Estimada</a></li>
<li class="chapter" data-level="6.21" data-path="polinômios-ortogonais.html"><a href="polinômios-ortogonais.html#gráficos"><i class="fa fa-check"></i><b>6.21</b> Gráficos</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="análise-conjunta.html"><a href="análise-conjunta.html"><i class="fa fa-check"></i><b>7</b> Análise conjunta</a><ul>
<li class="chapter" data-level="7.1" data-path="análise-conjunta.html"><a href="análise-conjunta.html#análise-conjunta-com-um-fator-qualitativo-dbc"><i class="fa fa-check"></i><b>7.1</b> Análise conjunta com um fator qualitativo (DBC)</a></li>
<li class="chapter" data-level="7.2" data-path="análise-conjunta.html"><a href="análise-conjunta.html#exemplo-1-8"><i class="fa fa-check"></i><b>7.2</b> Exemplo 1</a></li>
<li class="chapter" data-level="7.3" data-path="análise-conjunta.html"><a href="análise-conjunta.html#anova-individual"><i class="fa fa-check"></i><b>7.3</b> ANOVA individual</a><ul>
<li class="chapter" data-level="7.3.1" data-path="análise-conjunta.html"><a href="análise-conjunta.html#tempo-de-2-meses"><i class="fa fa-check"></i><b>7.3.1</b> Tempo de 2 meses</a></li>
<li class="chapter" data-level="7.3.2" data-path="análise-conjunta.html"><a href="análise-conjunta.html#tempo-de-4-meses"><i class="fa fa-check"></i><b>7.3.2</b> Tempo de 4 meses</a></li>
<li class="chapter" data-level="7.3.3" data-path="análise-conjunta.html"><a href="análise-conjunta.html#tempo-de-6-meses"><i class="fa fa-check"></i><b>7.3.3</b> Tempo de 6 meses</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="análise-conjunta.html"><a href="análise-conjunta.html#quadrado-do-resíduo-médio"><i class="fa fa-check"></i><b>7.4</b> Quadrado do resíduo médio</a></li>
<li class="chapter" data-level="7.5" data-path="análise-conjunta.html"><a href="análise-conjunta.html#gráfico-de-interação-2"><i class="fa fa-check"></i><b>7.5</b> Gráfico de interação</a></li>
<li class="chapter" data-level="7.6" data-path="análise-conjunta.html"><a href="análise-conjunta.html#análise-de-variância-conjunta"><i class="fa fa-check"></i><b>7.6</b> Análise de Variância conjunta</a></li>
<li class="chapter" data-level="7.7" data-path="análise-conjunta.html"><a href="análise-conjunta.html#conferindo-manualmente"><i class="fa fa-check"></i><b>7.7</b> Conferindo “Manualmente”</a></li>
<li class="chapter" data-level="7.8" data-path="análise-conjunta.html"><a href="análise-conjunta.html#grau-de-liberdade"><i class="fa fa-check"></i><b>7.8</b> Grau de liberdade</a><ul>
<li class="chapter" data-level="7.8.1" data-path="análise-conjunta.html"><a href="análise-conjunta.html#calculando-soma-de-quadrados"><i class="fa fa-check"></i><b>7.8.1</b> Calculando soma de quadrados</a></li>
<li class="chapter" data-level="7.8.2" data-path="análise-conjunta.html"><a href="análise-conjunta.html#calculando-quadrado-médio"><i class="fa fa-check"></i><b>7.8.2</b> Calculando quadrado médio</a></li>
<li class="chapter" data-level="7.8.3" data-path="análise-conjunta.html"><a href="análise-conjunta.html#teste-f-de-fischer"><i class="fa fa-check"></i><b>7.8.3</b> Teste F de Fischer</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="análise-conjunta.html"><a href="análise-conjunta.html#pressuposição-do-modelo"><i class="fa fa-check"></i><b>7.9</b> Pressuposição do modelo</a><ul>
<li class="chapter" data-level="7.9.1" data-path="análise-conjunta.html"><a href="análise-conjunta.html#normalidade-dos-erros-13"><i class="fa fa-check"></i><b>7.9.1</b> Normalidade dos erros</a></li>
<li class="chapter" data-level="7.9.2" data-path="análise-conjunta.html"><a href="análise-conjunta.html#gráfico-de-normalidade-1"><i class="fa fa-check"></i><b>7.9.2</b> Gráfico de normalidade</a></li>
<li class="chapter" data-level="7.9.3" data-path="análise-conjunta.html"><a href="análise-conjunta.html#homogeneidade-de-variâncias-6"><i class="fa fa-check"></i><b>7.9.3</b> Homogeneidade de variâncias</a></li>
<li class="chapter" data-level="7.9.4" data-path="análise-conjunta.html"><a href="análise-conjunta.html#independências-dos-erros-2"><i class="fa fa-check"></i><b>7.9.4</b> Independências dos erros</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="análise-conjunta.html"><a href="análise-conjunta.html#desdobramento"><i class="fa fa-check"></i><b>7.10</b> Desdobramento</a><ul>
<li class="chapter" data-level="7.10.1" data-path="análise-conjunta.html"><a href="análise-conjunta.html#desdobramento-do-comprimento-em-cada-nível-de-tempo"><i class="fa fa-check"></i><b>7.10.1</b> Desdobramento do Comprimento em cada nível de Tempo</a></li>
<li class="chapter" data-level="7.10.2" data-path="análise-conjunta.html"><a href="análise-conjunta.html#teste-de-comparação-múltipla-2"><i class="fa fa-check"></i><b>7.10.2</b> Teste de comparação múltipla</a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="análise-conjunta.html"><a href="análise-conjunta.html#tabela-final-1"><i class="fa fa-check"></i><b>7.11</b> Tabela Final</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Aplicações práticas do software R para Agronomia</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="esquema-fatorial-3-fatores" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Esquema Fatorial (3 Fatores)</h1>
<hr />
<p><br><br><br><br></p>
<p>Nos experimentos mais simples comparamos níveis (tratamentos) de apenas um fator; entretanto, existem casos em que dois ou mais fatores devem ser estudados simultaneamente para que possam nos conduzir a resultados de interesse;</p>
<p>Em geral, os experimentos fatoriais são mais eficientes para este tipo de experimento, pois estudam, ao mesmo tempo, os efeitos de dois ou mais fatores, cada um deles com dois ou mais níveis.</p>
<p>O fatorial é um tipo de esquema, ou seja, uma das maneiras de organizar os tratamentos e não um tipo de delineamento;</p>
<p>Os experimentos fatoriais são montados segundo um tipo de delineamento experimental;</p>
<p>Nos experimentos fatoriais, os tratamentos são obtidos pelas combinações dos níveis dos fatores.</p>
<p><br></p>
<hr />
<div id="tipos-de-efeitos-avaliados-1" class="section level2">
<h2><span class="header-section-number">4.1</span> Tipos de efeitos avaliados</h2>
<hr />
<p><br></p>
<ul>
<li><p>Efeito Principal: é o efeito de cada fator, independente do efeito dos outros fatores;</p></li>
<li><p>Efeito de Interação: é o efeito simultâneo dos fatores sobre a variável em estudo. Dizemos que ocorre interação entre os fatores quando os efeitos dos níveis de um fator são modificados pelos níveis do outro fator.</p></li>
</ul>
<p><br></p>
<hr />
</div>
<div id="vantagens-3" class="section level2">
<h2><span class="header-section-number">4.2</span> Vantagens</h2>
<hr />
<p><br></p>
<ol style="list-style-type: lower-alpha">
<li><p>Pode-se estudar dois ou mais fatores num único experimento.</p></li>
<li><p>Pode-se, por meio dos efeitos das interações, verificar se um fator é independente ou dependente do(s) outro(s).</p></li>
</ol>
<hr />
</div>
<div id="desvantagens-3" class="section level2">
<h2><span class="header-section-number">4.3</span> Desvantagens</h2>
<hr />
<p><br></p>
<ol style="list-style-type: lower-alpha">
<li><p>O número de tratamentos ou combinações de níveis de fatores cresce, rapidamente, com o aumento do número de níveis, em cada fator, ou mesmo com o aumento do número de fatores.</p></li>
<li><p>A interpretação dos resultados se torna mais difícil é medida que aumentamos o número de níveis e de fatores no experimento.</p></li>
</ol>
<p><br></p>
<hr />
</div>
<div id="modelo-estatístico-1" class="section level2">
<h2><span class="header-section-number">4.4</span> Modelo estatístico</h2>
<hr />
<p><br></p>
<p>As observações podem ser descritas pelo modelo estatístico linear:</p>
<center>
<p><span class="math inline">\(y_{ijk} = \mu+\beta_{1i}+\beta_{2j}+\beta_{3k}+(\beta_1\beta_2)_{ij}+(\beta_1\beta_3)_{ik}+(\beta_2\beta_3)_{jk}+(\beta_1\beta_2\beta_3)_{ijk}+\epsilon_{ijk}\)</span></p>
</center>
<ul>
<li>i = 1; 2; : : : ; a</li>
<li>j = 1; 2; : : : ; b</li>
<li>k = 1; 2; : : : ; c</li>
</ul>
<p>em que:</p>
<ul>
<li><span class="math inline">\(y_{ijk}\)</span> é o valor observado no i-ésimo nível do fator A, j-ésima nível do fator B e k-ésimo nível do fator C;</li>
<li><span class="math inline">\(\mu\)</span> é uma constante;</li>
<li><span class="math inline">\(\beta_{1i}\)</span> é o efeito do i-ésimo nível do fator A;</li>
<li><span class="math inline">\(\beta_{2j}\)</span> é o efeito do j-ésimo nível do fator B;</li>
<li><span class="math inline">\(\beta_{3k}\)</span> é o efeito do j-ésimo nível do fator C;</li>
<li><span class="math inline">\((\beta_1\beta_2)_ij\)</span> é o efeito da interação entre <span class="math inline">\(\beta_{1i}\)</span> e <span class="math inline">\(\beta_{2j}\)</span>;</li>
<li><span class="math inline">\((\beta_1\beta_3)_ik\)</span> é o efeito da interação entre <span class="math inline">\(\beta_{1i}\)</span> e <span class="math inline">\(\beta_{3j}\)</span>;</li>
<li><span class="math inline">\((\beta_2\beta_3)_jk\)</span> é o efeito da interação entre <span class="math inline">\(\beta_{2i}\)</span> e <span class="math inline">\(\beta_{3j}\)</span>;</li>
<li><span class="math inline">\((\beta_1\beta_2\beta_3)_{ijk}\)</span> é o efeito da interação entre <span class="math inline">\(\beta_{1i}\)</span>, <span class="math inline">\(\beta_{2j}\)</span> e <span class="math inline">\(\beta_{3k}\)</span>;</li>
<li><span class="math inline">\((\epsilon)ijk\)</span> é o componente de erro aleatório.</li>
</ul>
<p><br></p>
<hr />
</div>
<div id="hipóteses-e-modelo-3" class="section level2">
<h2><span class="header-section-number">4.5</span> Hipóteses e modelo</h2>
<hr />
<p><br></p>
<p>No experimento fatorial com 3 fatores, deseja-se testar a signicância de ambos os fatores.</p>
<p>No experimento fatorial com 2 fatores, deseja-se testar a signicância de ambos os fatores.</p>
<p>Há interesse em testar hipóteses sobre a igualdade dos efeitos do fator A, isto é:</p>
<ul>
<li>H0 : <span class="math inline">\(\beta_{11}\)</span> = <span class="math inline">\(\beta_{12}\)</span> = : : : <span class="math inline">\(\beta_{1a}\)</span> = 0</li>
<li>H1 : Pelo menos um <span class="math inline">\(\beta_{1i} \neq 0\)</span></li>
</ul>
<p>e a igualdade nos efeitos do fator B, ou seja:</p>
<ul>
<li>H0 : <span class="math inline">\(\beta_{21}\)</span> = <span class="math inline">\(\beta_{22}\)</span> = : : : <span class="math inline">\(\beta_{2b}\)</span> = 0</li>
<li>H1 : Pelo menos um <span class="math inline">\(\beta_{2j} \neq 0\)</span></li>
</ul>
<p>e, ainda, se há interação entre os fatores A e B:</p>
<ul>
<li>H0 : <span class="math inline">\((\beta_1\beta_2)_{ij}\)</span> = 0 para todo i ; j</li>
<li>H1 : Pelo menos um <span class="math inline">\((\beta_1\beta_2)_{ij} \neq 0\)</span></li>
</ul>
<p>e, ainda, se há interação entre os fatores A e C:</p>
<ul>
<li>H0 : <span class="math inline">\((\beta_1\beta_3)_{ik}\)</span> = 0 para todo i ; k</li>
<li>H1 : Pelo menos um <span class="math inline">\((\beta_1\beta_3)_{ik} \neq 0\)</span></li>
</ul>
<p>e, ainda, se há interação entre os fatores B e C:</p>
<ul>
<li>H0 : <span class="math inline">\((\beta_2\beta_3)_{jk}\)</span> = 0 para todo j ; k</li>
<li>H1 : Pelo menos um <span class="math inline">\((\beta_2\beta_3)_{jk} \neq 0\)</span></li>
</ul>
<p>e, ainda, se há interação entre os fatores A e B e C:</p>
<ul>
<li>H0 : <span class="math inline">\((\beta_1\beta_2\beta_3)_{ijk}\)</span> = 0 para todo i ; j; k</li>
<li>H1 : Pelo menos um <span class="math inline">\((\beta_1\beta_2\beta_3)_{ijk} \neq 0\)</span></li>
</ul>
<p><br><br><br></p>
<hr />
</div>
<div id="exemplo-1-5" class="section level2">
<h2><span class="header-section-number">4.6</span> Exemplo 1</h2>
<hr />
<p><br></p>
<p>Neste exemplo, vamos trabalhar com um experimento conduzido em delineamento inteiramente casualziado em esquema fatorial 3 x 3 x 3, em que todos os níveis dos fatores são qualitativos. Cada tratamento foi composto por quatro repetições, totalizando 108 parcelas. Os tratamentos consistem em:</p>
<ul>
<li>Fator 1: A1; A2 e A3</li>
<li>Fator 2: B1; B2 e B3</li>
<li>Fator 3: C1; C2 e C3</li>
</ul>
<p>Variável analisada: Produtividade em kg ha<span class="math inline">\(^{-1}\)</span></p>
<p><br><br></p>
</div>
<div id="conjunto-de-dados-6" class="section level2">
<h2><span class="header-section-number">4.7</span> Conjunto de dados</h2>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="esquema-fatorial-3-fatores.html#cb254-1"></a>RENDIMENTO=<span class="kw">c</span>(<span class="fl">4599.55</span>,<span class="fl">6203.50</span>,<span class="fl">4566.02</span>,<span class="fl">5616.38</span>,<span class="fl">4978.35</span>,<span class="fl">5126.15</span>,<span class="fl">4816.23</span>,<span class="fl">4251.00</span>,<span class="fl">4106.79</span>,</span>
<span id="cb254-2"><a href="esquema-fatorial-3-fatores.html#cb254-2"></a>             <span class="fl">4600.58</span>,<span class="fl">4012.14</span>,<span class="fl">4623.41</span>,<span class="fl">4274.16</span>,<span class="fl">4683.50</span>,<span class="fl">4433.33</span>,<span class="fl">4326.16</span>,<span class="fl">4932.66</span>,<span class="fl">5066.67</span>,</span>
<span id="cb254-3"><a href="esquema-fatorial-3-fatores.html#cb254-3"></a>             <span class="fl">4697.29</span>,<span class="fl">5011.38</span>,<span class="fl">5156.72</span>,<span class="fl">4744.21</span>,<span class="fl">4826.80</span>,<span class="fl">4663.26</span>,<span class="fl">4807.19</span>,<span class="fl">4377.19</span>,<span class="fl">4442.07</span>,</span>
<span id="cb254-4"><a href="esquema-fatorial-3-fatores.html#cb254-4"></a>             <span class="fl">4685.58</span>,<span class="fl">5066.90</span>,<span class="fl">5317.66</span>,<span class="fl">5144.19</span>,<span class="fl">4580.18</span>,<span class="fl">4860.37</span>,<span class="fl">5204.21</span>,<span class="fl">5146.19</span>,<span class="fl">5015.67</span>,</span>
<span id="cb254-5"><a href="esquema-fatorial-3-fatores.html#cb254-5"></a>             <span class="fl">5801.99</span>,<span class="fl">4668.05</span>,<span class="fl">5393.16</span>,<span class="fl">5282.27</span>,<span class="fl">5369.41</span>,<span class="fl">5494.43</span>,<span class="fl">4980.32</span>,<span class="fl">5715.76</span>,<span class="fl">4754.54</span>,</span>
<span id="cb254-6"><a href="esquema-fatorial-3-fatores.html#cb254-6"></a>             <span class="fl">5000.83</span>,<span class="fl">4664.11</span>,<span class="fl">4969.41</span>,<span class="fl">5315.43</span>,<span class="fl">4872.29</span>,<span class="fl">5546.79</span>,<span class="fl">4765.79</span>,<span class="fl">4649.63</span>,<span class="fl">4899.31</span>,</span>
<span id="cb254-7"><a href="esquema-fatorial-3-fatores.html#cb254-7"></a>             <span class="fl">4890.89</span>,<span class="fl">5117.10</span>,<span class="fl">4942.97</span>,<span class="fl">4548.97</span>,<span class="fl">4916.97</span>,<span class="fl">4225.38</span>,<span class="fl">4820.21</span>,<span class="fl">4150.44</span>,<span class="fl">4648.46</span>,</span>
<span id="cb254-8"><a href="esquema-fatorial-3-fatores.html#cb254-8"></a>             <span class="fl">4271.57</span>,<span class="fl">5143.54</span>,<span class="fl">4808.97</span>,<span class="fl">5459.66</span>,<span class="fl">4928.35</span>,<span class="fl">5224.70</span>,<span class="fl">4900.90</span>,<span class="fl">4770.88</span>,<span class="fl">4977.68</span>,</span>
<span id="cb254-9"><a href="esquema-fatorial-3-fatores.html#cb254-9"></a>             <span class="fl">5816.80</span>,<span class="fl">5107.11</span>,<span class="fl">5555.80</span>,<span class="fl">5767.65</span>,<span class="fl">5117.10</span>,<span class="fl">5573.08</span>,<span class="fl">5673.87</span>,<span class="fl">4859.00</span>,<span class="fl">4687.26</span>,</span>
<span id="cb254-10"><a href="esquema-fatorial-3-fatores.html#cb254-10"></a>             <span class="fl">5055.22</span>,<span class="fl">5235.22</span>,<span class="fl">4961.72</span>,<span class="fl">4984.93</span>,<span class="fl">5425.67</span>,<span class="fl">4978.33</span>,<span class="fl">5172.60</span>,<span class="fl">5328.07</span>,<span class="fl">4973.87</span>,</span>
<span id="cb254-11"><a href="esquema-fatorial-3-fatores.html#cb254-11"></a>             <span class="fl">5296.55</span>,<span class="fl">4928.01</span>,<span class="fl">4528.12</span>,<span class="fl">5337.93</span>,<span class="fl">5809.20</span>,<span class="fl">4914.70</span>,<span class="fl">5191.89</span>,<span class="fl">5261.24</span>,<span class="fl">5287.53</span>,</span>
<span id="cb254-12"><a href="esquema-fatorial-3-fatores.html#cb254-12"></a>             <span class="fl">5680.55</span>,<span class="fl">5080.06</span>,<span class="fl">5425.53</span>,<span class="fl">4949.13</span>,<span class="fl">5300.57</span>,<span class="fl">4481.23</span>,<span class="fl">5039.54</span>,<span class="fl">5223.75</span>,<span class="fl">4581.65</span>)</span>
<span id="cb254-13"><a href="esquema-fatorial-3-fatores.html#cb254-13"></a>FATOR1=<span class="kw">rep</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A1&quot;</span>,<span class="st">&quot;A2&quot;</span>,<span class="st">&quot;A3&quot;</span>), <span class="dt">e=</span><span class="dv">12</span>),<span class="dv">3</span>)</span>
<span id="cb254-14"><a href="esquema-fatorial-3-fatores.html#cb254-14"></a>FATOR2=<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;B1&quot;</span>,<span class="st">&quot;B2&quot;</span>,<span class="st">&quot;B3&quot;</span>), <span class="dt">e=</span><span class="dv">36</span>)</span>
<span id="cb254-15"><a href="esquema-fatorial-3-fatores.html#cb254-15"></a>FATOR3=<span class="kw">rep</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;C1&quot;</span>,<span class="st">&quot;c2&quot;</span>,<span class="st">&quot;c3&quot;</span>),<span class="dt">e=</span><span class="dv">4</span>),<span class="dv">9</span>)</span>
<span id="cb254-16"><a href="esquema-fatorial-3-fatores.html#cb254-16"></a>dados=<span class="kw">data.frame</span>(FATOR1,FATOR2,FATOR3,RENDIMENTO)</span></code></pre></div>
<p><br><br></p>
</div>
<div id="análise-exploratória-dos-dados" class="section level2">
<h2><span class="header-section-number">4.8</span> Análise Exploratória dos dados</h2>
<p><br></p>
<div id="análise-exploratória-dos-dados-geral" class="section level3">
<h3><span class="header-section-number">4.8.1</span> Análise Exploratória dos dados (Geral)</h3>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="esquema-fatorial-3-fatores.html#cb255-1"></a>media=<span class="kw">mean</span>(RENDIMENTO)</span>
<span id="cb255-2"><a href="esquema-fatorial-3-fatores.html#cb255-2"></a>variancia=<span class="kw">var</span>(RENDIMENTO)</span>
<span id="cb255-3"><a href="esquema-fatorial-3-fatores.html#cb255-3"></a>desvio=<span class="kw">sd</span>(RENDIMENTO)</span>
<span id="cb255-4"><a href="esquema-fatorial-3-fatores.html#cb255-4"></a>cv=desvio<span class="op">/</span>media<span class="op">*</span><span class="dv">100</span></span>
<span id="cb255-5"><a href="esquema-fatorial-3-fatores.html#cb255-5"></a><span class="kw">cbind</span>(media,variancia,desvio,cv)</span></code></pre></div>
<pre><code>##         media variancia   desvio       cv
## [1,] 4985.604  172705.4 415.5784 8.335568</code></pre>
<p><br></p>
</div>
<div id="análise-exploratória-dos-dados-fator-1" class="section level3">
<h3><span class="header-section-number">4.8.2</span> Análise Exploratória dos dados (Fator 1)</h3>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="esquema-fatorial-3-fatores.html#cb257-1"></a>media=<span class="kw">tapply</span>(RENDIMENTO, FATOR1,mean)</span>
<span id="cb257-2"><a href="esquema-fatorial-3-fatores.html#cb257-2"></a>variancia=<span class="kw">tapply</span>(RENDIMENTO, FATOR1,var)</span>
<span id="cb257-3"><a href="esquema-fatorial-3-fatores.html#cb257-3"></a>desvio=<span class="kw">tapply</span>(RENDIMENTO, FATOR1,sd)</span>
<span id="cb257-4"><a href="esquema-fatorial-3-fatores.html#cb257-4"></a>cv=desvio<span class="op">/</span>media<span class="op">*</span><span class="dv">100</span></span>
<span id="cb257-5"><a href="esquema-fatorial-3-fatores.html#cb257-5"></a><span class="kw">cbind</span>(media,variancia,desvio,cv)</span></code></pre></div>
<pre><code>##       media variancia   desvio        cv
## A1 5083.450  263382.8 513.2084 10.095670
## A2 4921.823  124860.9 353.3566  7.179384
## A3 4951.540  124516.3 352.8687  7.126444</code></pre>
<p><br>
### Análise Exploratória dos dados (Fator 2)</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="esquema-fatorial-3-fatores.html#cb259-1"></a>media=<span class="kw">tapply</span>(RENDIMENTO, FATOR2,mean)</span>
<span id="cb259-2"><a href="esquema-fatorial-3-fatores.html#cb259-2"></a>variancia=<span class="kw">tapply</span>(RENDIMENTO, FATOR2,var)</span>
<span id="cb259-3"><a href="esquema-fatorial-3-fatores.html#cb259-3"></a>desvio=<span class="kw">tapply</span>(RENDIMENTO, FATOR2,sd)</span>
<span id="cb259-4"><a href="esquema-fatorial-3-fatores.html#cb259-4"></a>cv=desvio<span class="op">/</span>media<span class="op">*</span><span class="dv">100</span></span>
<span id="cb259-5"><a href="esquema-fatorial-3-fatores.html#cb259-5"></a><span class="kw">cbind</span>(media,variancia,desvio,cv)</span></code></pre></div>
<pre><code>##       media variancia   desvio       cv
## B1 4804.546  184134.8 429.1093 8.931319
## B2 4969.199  150227.6 387.5920 7.799889
## B3 5183.069  119520.8 345.7178 6.670136</code></pre>
<p><br></p>
</div>
<div id="análise-exploratória-dos-dados-fator-3" class="section level3">
<h3><span class="header-section-number">4.8.3</span> Análise Exploratória dos dados (Fator 3)</h3>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="esquema-fatorial-3-fatores.html#cb261-1"></a>media=<span class="kw">tapply</span>(RENDIMENTO, FATOR3,mean)</span>
<span id="cb261-2"><a href="esquema-fatorial-3-fatores.html#cb261-2"></a>variancia=<span class="kw">tapply</span>(RENDIMENTO,FATOR3,var)</span>
<span id="cb261-3"><a href="esquema-fatorial-3-fatores.html#cb261-3"></a>desvio=<span class="kw">tapply</span>(RENDIMENTO,FATOR3,sd)</span>
<span id="cb261-4"><a href="esquema-fatorial-3-fatores.html#cb261-4"></a>cv=desvio<span class="op">/</span>media<span class="op">*</span><span class="dv">100</span></span>
<span id="cb261-5"><a href="esquema-fatorial-3-fatores.html#cb261-5"></a><span class="kw">cbind</span>(media,variancia,desvio,cv)</span></code></pre></div>
<pre><code>##       media variancia   desvio        cv
## C1 5021.699 277212.38 526.5096 10.484690
## c2 5081.969  97030.46 311.4971  6.129458
## c3 4853.145 124804.19 353.2764  7.279328</code></pre>
<p><br></p>
</div>
<div id="análise-exploratória-dos-dados-juntando-tratamentos" class="section level3">
<h3><span class="header-section-number">4.8.4</span> Análise Exploratória dos dados (Juntando tratamentos)</h3>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="esquema-fatorial-3-fatores.html#cb263-1"></a>media=<span class="kw">tapply</span>(RENDIMENTO, <span class="kw">paste</span>(FATOR1,FATOR2,FATOR3),mean)</span>
<span id="cb263-2"><a href="esquema-fatorial-3-fatores.html#cb263-2"></a>variancia=<span class="kw">tapply</span>(RENDIMENTO, <span class="kw">paste</span>(FATOR1,FATOR2,FATOR3),var)</span>
<span id="cb263-3"><a href="esquema-fatorial-3-fatores.html#cb263-3"></a>desvio=<span class="kw">tapply</span>(RENDIMENTO, <span class="kw">paste</span>(FATOR1,FATOR2,FATOR3),sd)</span>
<span id="cb263-4"><a href="esquema-fatorial-3-fatores.html#cb263-4"></a>cv=desvio<span class="op">/</span>media<span class="op">*</span><span class="dv">100</span></span>
<span id="cb263-5"><a href="esquema-fatorial-3-fatores.html#cb263-5"></a><span class="kw">cbind</span>(media,variancia,desvio,cv)</span></code></pre></div>
<pre><code>##             media variancia   desvio        cv
## A1 B1 C1 5246.363 644752.49 802.9648 15.305172
## A1 B1 c2 4792.932 146549.05 382.8173  7.987120
## A1 B1 c3 4335.730 103343.11 321.4702  7.414443
## A1 B2 C1 5286.368 219868.17 468.9010  8.870004
## A1 B2 c2 5389.980  95095.62 308.3758  5.721279
## A1 B2 c3 4847.222  26881.76 163.9566  3.382485
## A1 B3 C1 5561.840 104726.07 323.6141  5.818472
## A1 B3 c2 5305.762 147384.02 383.9063  7.235647
## A1 B3 c3 4984.855  52243.96 228.5694  4.585276
## A2 B1 C1 4429.288  33113.39 181.9708  4.108355
## A2 B1 c2 4927.000  26475.47 162.7128  3.302473
## A2 B1 c3 4847.748  46886.15 216.5321  4.466654
## A2 B2 C1 5125.075 135688.18 368.3588  7.187383
## A2 B2 c2 4889.233  36479.09 190.9950  3.906441
## A2 B2 c3 4658.573 115773.22 340.2546  7.303839
## A2 B3 C1 5140.382  44284.47 210.4388  4.093835
## A2 B3 c2 5131.625  44045.53 209.8703  4.089743
## A2 B3 c3 5147.488 303979.30 551.3432 10.710918
## A3 B1 C1 4578.007  40967.71 202.4048  4.421243
## A3 B1 c2 5027.233  99818.88 315.9413  6.284596
## A3 B1 c3 5056.610  23332.19 152.7488  3.020774
## A3 B2 C1 4472.670  98653.19 314.0910  7.022451
## A3 B2 c2 5085.130  81509.59 285.4988  5.614386
## A3 B2 c3 4968.540  36448.71 190.9155  3.842486
## A3 B3 C1 5355.302  48643.48 220.5527  4.118398
## A3 B3 c2 5188.823  45933.24 214.3204  4.130425
## A3 B3 c3 4831.542 127418.26 356.9569  7.388054</code></pre>
<p><br><br></p>
</div>
</div>
<div id="gráfico-exploratório" class="section level2">
<h2><span class="header-section-number">4.9</span> Gráfico exploratório</h2>
<p><br></p>
<div id="gráfico-de-caixas-6" class="section level3">
<h3><span class="header-section-number">4.9.1</span> Gráfico de caixas</h3>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="esquema-fatorial-3-fatores.html#cb265-1"></a><span class="kw">par</span>(<span class="dt">mai=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="fl">0.8</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</span>
<span id="cb265-2"><a href="esquema-fatorial-3-fatores.html#cb265-2"></a>car<span class="op">::</span><span class="kw">Boxplot</span>(RENDIMENTO<span class="op">~</span><span class="kw">paste</span>(FATOR1,FATOR2,FATOR3), <span class="dt">las=</span><span class="dv">2</span>, <span class="dt">xlab=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="livroagro_files/figure-html/unnamed-chunk-170-1.png" width="1152" /></p>
<p><br></p>
</div>
<div id="gráfico-de-interação-1" class="section level3">
<h3><span class="header-section-number">4.9.2</span> Gráfico de interação</h3>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="esquema-fatorial-3-fatores.html#cb266-1"></a>FATOR1=FATOR1</span>
<span id="cb266-2"><a href="esquema-fatorial-3-fatores.html#cb266-2"></a>FATOR2=FATOR2</span>
<span id="cb266-3"><a href="esquema-fatorial-3-fatores.html#cb266-3"></a>FATOR3=FATOR3</span>
<span id="cb266-4"><a href="esquema-fatorial-3-fatores.html#cb266-4"></a>RESP=RENDIMENTO</span>
<span id="cb266-5"><a href="esquema-fatorial-3-fatores.html#cb266-5"></a><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">bty=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb266-6"><a href="esquema-fatorial-3-fatores.html#cb266-6"></a><span class="kw">interaction.plot</span>(FATOR1,FATOR2,RESP, <span class="dt">ylab=</span><span class="st">&quot;Resposta&quot;</span>)</span>
<span id="cb266-7"><a href="esquema-fatorial-3-fatores.html#cb266-7"></a><span class="kw">interaction.plot</span>(FATOR2,FATOR1,RESP, <span class="dt">ylab=</span><span class="st">&quot;Resposta&quot;</span>)</span></code></pre></div>
<p><img src="livroagro_files/figure-html/unnamed-chunk-171-1.png" width="768" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="esquema-fatorial-3-fatores.html#cb267-1"></a><span class="kw">interaction.plot</span>(FATOR1,FATOR3,RESP, <span class="dt">ylab=</span><span class="st">&quot;Resposta&quot;</span>)</span>
<span id="cb267-2"><a href="esquema-fatorial-3-fatores.html#cb267-2"></a><span class="kw">interaction.plot</span>(FATOR2,FATOR1,RESP, <span class="dt">ylab=</span><span class="st">&quot;Resposta&quot;</span>)</span></code></pre></div>
<p><img src="livroagro_files/figure-html/unnamed-chunk-171-2.png" width="768" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="esquema-fatorial-3-fatores.html#cb268-1"></a><span class="kw">interaction.plot</span>(FATOR2,FATOR3,RESP, <span class="dt">ylab=</span><span class="st">&quot;Resposta&quot;</span>)</span>
<span id="cb268-2"><a href="esquema-fatorial-3-fatores.html#cb268-2"></a><span class="kw">interaction.plot</span>(FATOR3,FATOR2,RESP, <span class="dt">ylab=</span><span class="st">&quot;Resposta&quot;</span>)</span></code></pre></div>
<p><img src="livroagro_files/figure-html/unnamed-chunk-171-3.png" width="768" style="display: block; margin: auto;" /></p>
<p><br></p>
</div>
</div>
<div id="análise-de-variância-8" class="section level2">
<h2><span class="header-section-number">4.10</span> Análise de variância</h2>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="esquema-fatorial-3-fatores.html#cb269-1"></a>modelo=<span class="kw">aov</span>(RESP<span class="op">~</span>FATOR1<span class="op">*</span>FATOR2<span class="op">*</span>FATOR3)</span>
<span id="cb269-2"><a href="esquema-fatorial-3-fatores.html#cb269-2"></a><span class="kw">anova</span>(modelo)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: RESP
##                      Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## FATOR1                2  532881  266440  2.4550  0.092230 .  
## FATOR2                2 2593572 1296786 11.9487 2.836e-05 ***
## FATOR3                2 1012836  506418  4.6662  0.012078 *  
## FATOR1:FATOR2         4  568196  142049  1.3089  0.273715    
## FATOR1:FATOR3         4 2177621  544405  5.0162  0.001158 ** 
## FATOR2:FATOR3         4  548172  137043  1.2627  0.291478    
## FATOR1:FATOR2:FATOR3  8 2255321  281915  2.5976  0.014010 *  
## Residuals            81 8790883  108529                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>O que se observa nesta análise:</p>
<ul>
<li>Efeito de interação tripla: F1 x F2 x F3;</li>
<li>Efeito de interação dupla: F1 x F3;</li>
<li>Efeito isolado dos fatores F2 e F3.</li>
</ul>
<p><br><br></p>
</div>
<div id="pressuposições-7" class="section level2">
<h2><span class="header-section-number">4.11</span> Pressuposições</h2>
<p><br></p>
<div id="normalidade-dos-erros-10" class="section level3">
<h3><span class="header-section-number">4.11.1</span> Normalidade dos erros</h3>
<p>Análise gráfica e pelo teste de normalidade de Shapiro-Wilk</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="esquema-fatorial-3-fatores.html#cb271-1"></a><span class="kw">shapiro.test</span>(modelo<span class="op">$</span>residuals)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  modelo$residuals
## W = 0.98386, p-value = 0.217</code></pre>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="esquema-fatorial-3-fatores.html#cb273-1"></a>hnp<span class="op">::</span><span class="kw">hnp</span>(modelo)</span></code></pre></div>
<pre><code>## Gaussian model (aov object)</code></pre>
<p><img src="livroagro_files/figure-html/unnamed-chunk-173-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Como p-valor calculado (<span class="math inline">\(p=0.217\)</span>) é menor que o nível de significância adotado (<span class="math inline">\(\alpha=0.05\)</span>), não rejeita-se <span class="math inline">\(H_0\)</span>. Logo, os erros podem ser considerados normais</p>
<p><br></p>
</div>
<div id="homogeneidade-das-variâncias-5" class="section level3">
<h3><span class="header-section-number">4.11.2</span> Homogeneidade das variâncias</h3>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="esquema-fatorial-3-fatores.html#cb275-1"></a><span class="kw">bartlett.test</span>(modelo<span class="op">$</span>residuals<span class="op">~</span><span class="kw">paste</span>(FATOR1,FATOR2,FATOR3))</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  modelo$residuals by paste(FATOR1, FATOR2, FATOR3)
## Bartlett&#39;s K-squared = 26.434, df = 26, p-value = 0.4394</code></pre>
<p>Como p-valor calculado (<span class="math inline">\(p=0.4394\)</span>) é menor que o nível de significância adotado (<span class="math inline">\(\alpha=0.05\)</span>), não rejeita-se <span class="math inline">\(H_0\)</span>. Logo, as variâncias podem ser consideradas homogêneas.</p>
<p><br></p>
</div>
<div id="independência-dos-erros-7" class="section level3">
<h3><span class="header-section-number">4.11.3</span> Independência dos erros</h3>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="esquema-fatorial-3-fatores.html#cb277-1"></a>lmtest<span class="op">::</span><span class="kw">dwtest</span>(modelo)</span></code></pre></div>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  modelo
## DW = 2.8115, p-value = 0.9728
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p>Como p-valor calculado (<span class="math inline">\(p=0.9728\)</span>) é menor que o nível de significância adotado (<span class="math inline">\(\alpha=0.05\)</span>), não rejeita-se <span class="math inline">\(H_0\)</span>. Logo, os erros podem ser considerados independentes.</p>
<p><br></p>
</div>
<div id="gráfico-de-residuos-padronizados" class="section level3">
<h3><span class="header-section-number">4.11.4</span> Gráfico de residuos padronizados</h3>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="esquema-fatorial-3-fatores.html#cb279-1"></a>a=<span class="kw">anova</span>(modelo)</span>
<span id="cb279-2"><a href="esquema-fatorial-3-fatores.html#cb279-2"></a><span class="kw">plot</span>(modelo<span class="op">$</span>residuals<span class="op">/</span><span class="kw">sqrt</span>(a<span class="op">$</span><span class="st">`</span><span class="dt">Mean Sq</span><span class="st">`</span>[<span class="dv">7</span>]),</span>
<span id="cb279-3"><a href="esquema-fatorial-3-fatores.html#cb279-3"></a>     <span class="dt">ylab=</span><span class="st">&quot;Resíduos padronizados&quot;</span>,</span>
<span id="cb279-4"><a href="esquema-fatorial-3-fatores.html#cb279-4"></a>     <span class="dt">pch=</span><span class="dv">16</span>,</span>
<span id="cb279-5"><a href="esquema-fatorial-3-fatores.html#cb279-5"></a>     <span class="dt">las=</span><span class="dv">1</span>,</span>
<span id="cb279-6"><a href="esquema-fatorial-3-fatores.html#cb279-6"></a>     <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb279-7"><a href="esquema-fatorial-3-fatores.html#cb279-7"></a><span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">3</span>,<span class="op">-</span><span class="dv">3</span>),</span>
<span id="cb279-8"><a href="esquema-fatorial-3-fatores.html#cb279-8"></a>       <span class="dt">lty=</span><span class="dv">2</span>,</span>
<span id="cb279-9"><a href="esquema-fatorial-3-fatores.html#cb279-9"></a>       <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="livroagro_files/figure-html/unnamed-chunk-176-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br><br></p>
</div>
</div>
<div id="teste-de-comparação" class="section level2">
<h2><span class="header-section-number">4.12</span> Teste de comparação</h2>
<p><br></p>
<div id="pacote-expdes.pt" class="section level3">
<h3><span class="header-section-number">4.12.1</span> Pacote ExpDes.pt</h3>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="esquema-fatorial-3-fatores.html#cb280-1"></a><span class="kw">library</span>(ExpDes.pt)</span>
<span id="cb280-2"><a href="esquema-fatorial-3-fatores.html#cb280-2"></a><span class="kw">fat3.dic</span>(FATOR1,FATOR2,FATOR3,RESP)</span></code></pre></div>
<pre><code>## ------------------------------------------------------------------------
## Legenda:
## FATOR 1:  F1 
## FATOR 2:  F2 
## FATOR 3:  F3 
## ------------------------------------------------------------------------
## 
## ------------------------------------------------------------------------
## Quadro da analise de variancia
## ------------------------------------------------------------------------
##           GL         SQ            QM      Fc  Pr&gt;Fc
## F1         2   532880.7  266440.36564   2.455 0.0922
## F2         2  2593572.1 1296786.06573 11.9487      0
## F3         2  1012836.0  506417.98458  4.6662 0.0121
## F1*F2      4   568195.7  142048.92116  1.3089 0.2737
## F1*F3      4  2177620.9  544405.22841  5.0162 0.0012
## F2*F3      4   548172.3  137043.08275  1.2627 0.2915
## F1*F2*F3   8  2255321.1   281915.1382  2.5976  0.014
## Residuo   81  8790882.9  108529.41824               
## Total    107 18479481.7                             
## ------------------------------------------------------------------------
## CV = 0.03 %
## 
## ------------------------------------------------------------------------
## Teste de normalidade dos residuos (Shapiro-Wilk)
## valor-p:  0.2169645 
## De acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.
## ------------------------------------------------------------------------
## 
## 
## 
## Interacao F1*F2*F3  significativa: desdobrando a interacao
## ------------------------------------------------------------------------
## 
## Desdobrando  F1  dentro de cada nivel de  F2 e F3 
## ------------------------------------------------------------------------
## ------------------------------------------------------------------------
## Quadro da analise de variancia
## ------------------------------------------------------------------------
##           GL         SQ        QM       Fc    Pr&gt;Fc
## F1: B1 C1  2 1515236.80 757618.40 6.980765 0.001596
## F1: B1 c2  2  110556.18  55278.09 0.509337 0.602805
## F1: B1 c3  2 1100604.58 550302.29 5.070536 0.008418
## F1: B2 C1  2 1485001.57 742500.78  6.84147 0.001797
## F1: B2 c2  2  509409.88 254704.94 2.346875 0.102142
## F1: B2 c3  2  195182.15  97591.07 0.899213 0.410912
## F1: B3 C1  2  355299.69 177649.85 1.636882 0.200956
## F1: B3 c2  2   63027.18  31513.59 0.290369 0.748763
## F1: B3 c3  2  199700.39  99850.20 0.920029 0.402631
## Residuo   81 8790882.88 108529.42                  
## ------------------------------------------------------------------------
## 
## 
## 
##  F1  dentro da combinacao dos niveis  B1  de  F2  e  C1  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     A1      5246.363 
##  b    A3      4578.007 
##  b    A2      4429.288 
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B1  de  F2  e  c2  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       A1   4792.932
## 2       A2   4927.000
## 3       A3   5027.233
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B1  de  F2  e  c3  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     A3      5056.61 
## ab    A2      4847.748 
##  b    A1      4335.73 
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B2  de  F2  e  C1  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     A1      5286.368 
## a     A2      5125.075 
##  b    A3      4472.67 
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B2  de  F2  e  c2  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       A1   5389.980
## 2       A2   4889.233
## 3       A3   5085.130
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B2  de  F2  e  c3  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       A1   4847.222
## 2       A2   4658.573
## 3       A3   4968.540
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B3  de  F2  e  C1  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       A1   5561.840
## 2       A2   5140.382
## 3       A3   5355.302
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B3  de  F2  e  c2  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       A1   5305.762
## 2       A2   5131.625
## 3       A3   5188.823
## ------------------------------------------------------------------------
## 
## 
##  F1  dentro da combinacao dos niveis  B3  de  F2  e  c3  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       A1   4984.855
## 2       A2   5147.488
## 3       A3   4831.542
## ------------------------------------------------------------------------
## 
## 
## 
## Desdobrando  F2  dentro de cada nivel de  F1 e F3 
## ------------------------------------------------------------------------
## ------------------------------------------------------------------------
## Quadro da analise de variancia
## ------------------------------------------------------------------------
##           GL         SQ        QM       Fc    Pr&gt;Fc
## F2: A1 C1  2  236015.40 118007.70 1.087334 0.341983
## F2: A1 c2  2  835403.88 417701.94 3.848744 0.025307
## F2: A1 c3  2  935907.40 467953.70 4.311768 0.016617
## F2: A2 C1  2 1320014.22 660007.11 6.081366 0.003462
## F2: A2 c2  2  136069.20  68034.60 0.626877 0.536829
## F2: A2 c3  2  486225.50 243112.75 2.240063 0.113007
## F2: A3 C1  2 1859098.18 929549.09  8.56495 0.000422
## F2: A3 c2  2   53620.78  26810.39 0.247033 0.781701
## F2: A3 c3  2  102906.69  51453.35 0.474096 0.624164
## Residuo   81 8790882.88 108529.42                  
## ------------------------------------------------------------------------
## 
## 
## 
##  F2  dentro da combinacao dos niveis  A1  de  F1  e  C1  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       B1   5246.363
## 2       B2   5286.368
## 3       B3   5561.840
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A1  de  F1  e  c2  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     B2      5389.98 
## ab    B3      5305.762 
##  b    B1      4792.932 
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A1  de  F1  e  c3  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     B3      4984.855 
## ab    B2      4847.222 
##  b    B1      4335.73 
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A2  de  F1  e  C1  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     B3      5140.382 
## a     B2      5125.075 
##  b    B1      4429.288 
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A2  de  F1  e  c2  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       B1   4927.000
## 2       B2   4889.233
## 3       B3   5131.625
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A2  de  F1  e  c3  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       B1   4847.748
## 2       B2   4658.573
## 3       B3   5147.488
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A3  de  F1  e  C1  de  F3 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     B3      5355.302 
##  b    B1      4578.007 
##  b    B2      4472.67 
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A3  de  F1  e  c2  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       B1   5027.233
## 2       B2   5085.130
## 3       B3   5188.823
## ------------------------------------------------------------------------
## 
## 
##  F2  dentro da combinacao dos niveis  A3  de  F1  e  c3  de  F3 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       B1   5056.610
## 2       B2   4968.540
## 3       B3   4831.542
## ------------------------------------------------------------------------
## 
## Desdobrando  F3  dentro de cada nivel de  F1 e F2 
## ------------------------------------------------------------------------
## ------------------------------------------------------------------------
## Quadro da analise de variancia
## ------------------------------------------------------------------------
##           GL           SQ          QM       Fc    Pr&gt;Fc
## F3: A1 B1  2 1658512.5880 829256.2940 7.640843 0.000912
## F3: A1 B2  2  664226.1133 332113.0567  3.06012 0.052338
## F3: A1 B3  2  668625.3330 334312.6665 3.080388 0.051362
## F3: A2 B1  2  572143.2840 286071.6420  2.63589 0.077796
## F3: A2 B2  2  435267.0706 217633.5353 2.005295 0.141249
## F3: A2 B3  2     505.0583    252.5292 0.002327 0.997676
## F3: A3 B1  2  575635.3215 287817.6608 2.651978  0.07663
## F3: A3 B2  2  846116.7155 423058.3577 3.898098 0.024192
## F3: A3 B3  2  572918.8352 286459.4176 2.639463 0.077536
## Residuo   81 8790882.8771 108529.4182                  
## ------------------------------------------------------------------------
## 
## 
## 
##  F3  dentro da combinacao dos niveis  A1  de  F1  e  B1  de  F2 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     C1      5246.363 
## ab    c2      4792.932 
##  b    c3      4335.73 
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A1  de  F1  e  B2  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   5286.368
## 2       c2   5389.980
## 3       c3   4847.222
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A1  de  F1  e  B3  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   5561.840
## 2       c2   5305.762
## 3       c3   4984.855
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A2  de  F1  e  B1  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   4429.288
## 2       c2   4927.000
## 3       c3   4847.748
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A2  de  F1  e  B2  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   5125.075
## 2       c2   4889.233
## 3       c3   4658.573
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A2  de  F1  e  B3  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   5140.382
## 2       c2   5131.625
## 3       c3   5147.488
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A3  de  F1  e  B1  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   4578.007
## 2       c2   5027.233
## 3       c3   5056.610
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A3  de  F1  e  B2  de  F2 
## ------------------------------------------------------------------------
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a     c2      5085.13 
## ab    c3      4968.54 
##  b    C1      4472.67 
## ------------------------------------------------------------------------
## 
## 
##  F3  dentro da combinacao dos niveis  A3  de  F1  e  B3  de  F2 
## 
## De acordo com o teste F, as medias desse fator sao estatisticamente iguais.
## ------------------------------------------------------------------------
##     Niveis     Medias
## 1       C1   5355.302
## 2       c2   5188.823
## 3       c3   4831.542
## ------------------------------------------------------------------------</code></pre>
<p><br></p>
</div>
<div id="pacote-easyanova" class="section level3">
<h3><span class="header-section-number">4.12.2</span> Pacote easyanova</h3>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="esquema-fatorial-3-fatores.html#cb282-1"></a><span class="kw">library</span>(easyanova)</span>
<span id="cb282-2"><a href="esquema-fatorial-3-fatores.html#cb282-2"></a><span class="kw">ea2</span>(<span class="kw">data.frame</span>(FATOR1,FATOR2,FATOR3,RESP),<span class="dt">design =</span> <span class="dv">7</span>)</span></code></pre></div>
<p><strong>Obs.</strong> Em função da saída extensa da <em>package</em> easyanova, foi ocultado o resultado do mesmo.</p>
<p><br></p>
</div>
</div>
<div id="tabela-final" class="section level2">
<h2><span class="header-section-number">4.13</span> Tabela Final</h2>
<p><br></p>
<p><strong>Sugestão de tabela</strong></p>
<table>
<colgroup>
<col width="12%" />
<col width="12%" />
<col width="24%" />
<col width="24%" />
<col width="24%" />
</colgroup>
<thead>
<tr class="header">
<th>FATOR1</th>
<th>FATOR 2</th>
<th></th>
<th>FATOR 3</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>C1</td>
<td>C2</td>
<td>C3</td>
</tr>
<tr class="even">
<td>A1</td>
<td><ul>
<li>B1</li>
<li>B2</li>
<li>B3</li>
</ul></td>
<td><ul>
<li>5245,36 <em>a</em>aA</li>
<li>5286,37 <em>a</em>aA</li>
<li>5561,84 <em>a</em>aA</li>
</ul></td>
<td><ul>
<li>4335,73 <em>b</em>bB</li>
<li>4847,22 <em>a</em>abA</li>
<li>4984,86 <em>a</em>aA</li>
</ul></td>
<td><ul>
<li>4792,93 <em>a</em>aAB</li>
<li>5389,98 <em>a</em>aA</li>
<li>5305,76 <em>a</em>abA</li>
</ul></td>
</tr>
<tr class="odd">
<td>A2</td>
<td><ul>
<li>B1</li>
<li>B2</li>
<li>B3</li>
</ul></td>
<td><ul>
<li>4429,29 <em>b</em>bA</li>
<li>5125,08 <em>a</em>aA</li>
<li>5140,38 <em>a</em>aA</li>
</ul></td>
<td><ul>
<li>4847,75 <em>ab</em>aA</li>
<li>4658,57 <em>a</em>aA</li>
<li>5147,49 <em>a</em>aA</li>
</ul></td>
<td><ul>
<li>4927,00 <em>a</em>aA</li>
<li>4889,23 <em>a</em>aA</li>
<li>5131,63 <em>a</em>aA</li>
</ul></td>
</tr>
<tr class="even">
<td>A3</td>
<td><ul>
<li>B1</li>
<li>B2</li>
<li>B3</li>
</ul></td>
<td><ul>
<li>4578,00 <em>b</em>bA</li>
<li>4472,67 <em>b</em>bB</li>
<li>5355,30 <em>a</em>aA</li>
</ul></td>
<td><ul>
<li>5056,61 <em>a</em>aA</li>
<li>4968,54 <em>a</em>aAB</li>
<li>4831,54 <em>a</em>aA</li>
</ul></td>
<td><ul>
<li>5027,23 <em>a</em>aA</li>
<li>5085,13 <em>a</em>aA</li>
<li>5188,82 <em>a</em>aA</li>
</ul></td>
</tr>
<tr class="odd">
<td><ul>
<li>F1</li>
<li>F2</li>
<li>F3</li>
<li>F1xF2</li>
<li>F1xF3</li>
<li>F1xF3</li>
<li>F1xF2xF3</li>
</ul></td>
<td><ul>
<li>0,0922<span class="math inline">\(^{ns}\)</span></li>
<li>0,0000<span class="math inline">\(^{**}\)</span></li>
<li>0,0121<span class="math inline">\(^*\)</span></li>
<li>0,2737<span class="math inline">\(^{ns}\)</span></li>
<li>0,0012<span class="math inline">\(^{**}\)</span></li>
<li>0,2915<span class="math inline">\(^{ns}\)</span></li>
<li>0,0140<span class="math inline">\(^*\)</span></li>
</ul></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Médias seguidas de mesma letra maiúscula na linha, minúscula em itálico dentro dos níveis do Fator 2, e minúsculo dentro dos níveis do Fator 1 não diferem pelo teste de Tukey (<span class="math inline">\(p\leqslant 0,05\)</span>). <span class="math inline">\(^*,^{**},^{ns}\)</span>, significativo a 5%, 1% e não significativo pelo teste F.</p>
<p><br><br><br><br></p>
<hr />
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="delineamento-inteiramente-casualizado.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="esquema-de-parcelas-subdivididas.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["livroagro.pdf", "livroagro.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
